### PR TITLE
Modularized library and created test app

### PR DESCRIPTION
**Pull request by EmmanuelMess**
I created 2 modules, library and app.

### CODE REVIEW

**Comment by lapism** [comment]
Hi. Sorry but I do not want any kind of sample app here. I will provide ASAP better README.

**Comment by EmmanuelMess** [comment]
And the modularization? (Only the library)

**Comment by EmmanuelMess** [comment]
Also, might I ask how do you test?

**Comment by lapism** [comment]
I have a private bigger project ;). Modularization...everything was in one really big commit and that is hard to check, sorry.

**Comment by EmmanuelMess** [comment]
Ok, I understand, although it seems that you should upload the bigger project if you want other people contributing.

**Pull request closed without merging**
