### PR TITLE
Added an option to show progress while searching

### PR DESCRIPTION
**Pull request by HusseinElFeky**
This option is extremely useful for those who handle very large amount of suggestions. I have also removed the extra spaces before the code in ReadMe and replaced lambda expressions with regular expressions.

### CODE REVIEW

**Comment by lapism** [comment]
Nice. You are very helpful. Give me one or two days to check everything and I will release a new version.

**Comment by HusseinElFeky** [comment]
OK, sweet!

**Comment by lapism** [comment]
Hey, I reviewed your changes twice and it looks OK, so Alpha 6 is out.

**Comment by Dahnark** [comment]
can you add a changelog?

**Comment by HusseinElFeky** [comment]
@Dahnark Well I think the changelog would be something like:
1. Fixed the divider between SearchView and SearchItems not showing.
2. Added an option to show progress while searching.

Not sure if there is something else.

**Pull request merged**
