### PR TITLE
Added RTL back icon

### PR DESCRIPTION
**Pull request by alirezaafkar**
I forgot to add the icon in my previous pull request.
I also fixed the error in editor when voice is true

### CODE REVIEW

**Comment by lapism** [comment]
Thanks.

**Comment by lapism** [comment]
Hi, I got some feedback and it looks like RTL reveal animation in your pull request is not correct. Or is? Anyway, thank you very much for RTL support.

**Comment by alirezaafkar** [comment]
Hi, it's working well for me! What's wrong? Any video or image?

**Comment by lapism** [comment]
Nothing, just text feedback. I will see if I will get more from this guy. Maybe that missing arrow, I do not know. Btw. 3.3.1 will be soon with your arrow.

**Pull request merged**
