### PR TITLE
Feature/search view border color

### PR DESCRIPTION
**Pull request by EligijusStarinskas**

### CODE REVIEW

**Comment by lapism** [comment]
You needed it right ? :) I will push it to master and new version will be tomorrow.

**Comment by EligijusStarinskas** [comment]
Hey, yup, it would be nice to have an option to change a color around searchView. Thanks.

BTW, Nice project!

**Comment by lapism** [comment]
Why not. Thanks :).

**Comment by lapism** [comment]
So I have tried it. And it was weird and did not work nice. So I added option to change background shadow color. Still version 2.0.1, only reuploaded.

**Comment by EligijusStarinskas** [comment]
screen shot 2016-02-17 at 10 28 48

I have a specific situation (you can see in the image).
The problem is that toolbar's height is not the same as searchView's height. It is hard to calculate a height that will fully cover searchView's background.

I tried to put SearchView in another layout which has specific colour, but when SearchView is active that layout stretches and whole screen is covered by that colour. So I decided to modify your library and add an empty view, which has exact size as SearchView does.

Writing this comment I realised that I can do the same in my project as I can use dimensions provided in your library..

Anyways, thanks

**Comment by lapism** [comment]
Hi. 
Library was created as the best copy of what you can see in Play Store App. 
So that means I have done it with exactly same dimensions and same shadow empty view under it. But I understand where your problems started and why. Toolbar should have 56dp/64dp and SearchView has everytime only 48dp, but with different margins for toolbar and menu item versions. 

Maybe in the future I will decide to remove that shadow empty view, which covers screen. But right now I will try to fix every damn bug in the project and after that I will add more functionality.

**Pull request merged**
