### PR TITLE
Various fixes

### PR DESCRIPTION
**Pull request by AllanWang**
This pull request will contain various fixes/updates as I go.
Currently, it updates to readme to fix some spacings, properly show the screenshots, and give info on `setVersion`, which is important in getting the menuitem style.

Hopefully helps #225 since the example is actually correct

### CODE REVIEW

**Comment by AllanWang** [comment]
Add delayed query callback, addressing #248

**Comment by AllanWang** [comment]
Added gradle wrappers, since a default one is needed when importing android projects. You should also look into not gitignoring all .idea files, since it might not be necessary

**Comment by AllanWang** [comment]
I have found out that there exists things like [debouncing in observables](http://stackoverflow.com/questions/21890338/when-should-one-use-rxjava-observable-and-when-simple-callback-on-android) which voids the need for a delay functionality.

**Comment by AllanWang** [comment]
@lapism would you also be interested in a pull request to update the sample activities? Namely one where the base activity only holds the common portions to set up the drawers/tabs etc. Setting up SearchView will be separate in each activity so it is easier for users to see what they need to do to set it up

**Comment by lapism** [comment]
sure ... I will do next big update in two weeks.

**Pull request merged**
