### PR TITLE
pull request

### PR DESCRIPTION
**Pull request by lucasfernog**
fix search height landscape
searched query update _id

### CODE REVIEW

**Comment by lapism** [comment]
Hi, Why dimension is changed? It should be always 48dp.

**Comment by lucasfernog** [comment]
img_20160724_130640

**Comment by lapism** [comment]
And this is not correct, because you probably use ?attr/actionBarSize

**Comment by lapism** [comment]
And toolbar with SearchView must have 56/64 dp for classic and sw600dp.

**Comment by lucasfernog** [comment]
you're right, weird

**Comment by lapism** [comment]
You can see it in sample project :)

**Comment by lucasfernog** [comment]
Also, the keyboard should close when the recycler view is scrolled.

```
mRecyclerView.addOnScrollListener(new RecyclerView.OnScrollListener()
        {
            @Override
            public void onScrollStateChanged(RecyclerView recyclerView, int newState)
            {
                if (newState == RecyclerView.SCROLL_STATE_DRAGGING)
                    hideKeyboard();
            }
        });
```

**Comment by lapism** [comment]
Thanks. I will check everything ASAP.

**Comment by AlphabetDev** [comment]
The problem still exists in the current version - why did you remove the dimens.xml from the commit from lucasfernog immadiately after you merged it into the master? It solves the problem with having a smaller toolbar in landscape mode

**Comment by lapism** [comment]
Because you have to use 56dp/64dp instead ?attr/actionBarSize.

**Comment by lapism** [comment]
And toolbar with SearchView must have 56/64 dp for classic and sw600dp.

**Comment by AlphabetDev** [comment]
Can you give an example of how to do it right? I get literly the same result as lucasfernog if using in landscape mode.

**Comment by AlphabetDev** [comment]
Your lib is perfect despite that fact.

**Comment by lapism** [comment]
in sample app there is  <dimen name="toolbar_height">64dp</dimen> for tablets (sw600dp) and  <dimen name="toolbar_height">56dp</dimen> for mobiles. Use it for height of toolbar.

So in every mode there will be always 56/64dp.

**Comment by AlphabetDev** [comment]
In material design guideline, Google tells to use 48dp for mobile landscape. It would be a pleasure to give us the option to set the height of toolbar. Is this possible? I want to follow Material Guidelines with my app.

**Comment by AlphabetDev** [comment]
https://material.google.com/layout/structure.html

**Comment by lapism** [comment]
This lib is exact copy of what you can see in Play Store. So I can give you option to change height of whole SearchView but you have to wait till next release :).

**Comment by lapism** [comment]
And btw. 48dp seems to be only for desktop.

**Comment by AlphabetDev** [comment]
Maybe you can find a solution which works out of the box depending on what height the toolbar is actually. That would be a big enhancement. Great work anyway. Considering google guidelines 48dp is for mobile landscape and I can verify that AppCompat Toolbar is 48dp on mobile landscape. while it is 56dp on mobile portrait.

**Comment by lapism** [comment]
OK, in next release will be method setHeight :).

**Pull request merged**
