### PR TITLE
added getters for lists (handy for customizing the adapter)

### PR DESCRIPTION
**Pull request by BoldijarPaul**
I think that some getters for the lists will be handy for the developers that want to customize the behavior of the adapter.

In my case, trying to add custom filtering.

### CODE REVIEW

**Comment by lapism** [comment]
Thank you. But I will solve every issue and pull request after I will be done with diploma thesis :). But I have already some improved version of my library in my custom repository, so next release will be ASAP.

**Comment by mparodi** [comment]
+1

I'm trying to disable the filter overriding getFilter() but I couldn't do that since I don't have access to /mHistoryDatabase/ and /mResultList/ from my extended adapter.

**Comment by lapism** [comment]
why not ;). Today I am gonna release it.

**Comment by mparodi** [comment]
I've seen you pushed a new release today, thanks for that! The bad news is it's still not possible to alter the way the lib filters suggestions, it's more complicated than it looks.

The problem is that by design _onQueryTextChange_ is called AFTER the filter has been applied to the predefined set of suggestions, but in most cases it's a bad idea to download the full list of static suggestions. It's a better idea to query the server for suggestions as the user type, but there's no way to trigger the query on time.

I've forked the repository to update the code with the intention to send a pull request later today, but it's been impossible to make it work on Android Studio. Do you mind adding me on Skype or sending me an e-mail to discuss it quicker? I couldn't find your e-mail here on Github.

mparodilabs at gmail dot com
mparodilabs on Skype

Thanks!

**Comment by lapism** [comment]
Hi, fork the project, then use GitHub application and send me a pull request. E-mail is slow and Skype is private for me :).

**Pull request merged**
